### ISSUE TITLE
Autocomplete suggestions are not displaying (Android)

### ISSUE THREAD

**Issue by edwinjue** [l-urence/react-native-autocomplete-input#20] opened 2016-09-16 03:58 UTC
I tried running your Example.js on both a real device and an android emulator and the autocomplete window does not show up when I enter the letter 'P' in the input field. What I'm expecting is a dropdown that shows the 3 titles as per your animated gif. Is there a known issue with android or any reason why the example isn't working as expected?

I also tried adding a console.log to the 'onShowResult' event and it never outputs to Logcat (which makes me believe something isn't right)

Thanks in advance

**Comment by binzailani3136** [comment] 2016-09-16 14:49
I also have same issue. If you solved it, let me know. I waste many time for fixing this issue.

**Comment by l-urence** [comment] 2016-09-19 05:55
Thanks for reporting the issue! Android is such a PITA. Tried to run it in the emulator ether the app or the emulator os constantly crashing. As soon I have some more time I will investigate further.

**Comment by edwinjue** [comment] 2016-09-19 17:31
@l-urence, it works! But the <Autocomplete /> component  must be enclosed in a <View> with style={{zIndex:1}} as per solution to #21. Please keep us updated when the fix is released.

**Comment by l-urence** [comment] 2016-09-20 06:52
@edwinjue good to now. I will try to fix this latest next weekend.

**Comment by l-urence** [comment] 2016-09-25 13:09
The problem with Android is that it doesn't  support overflows (or at least not in RN). This is the reason why there is no suggestion list popping-up, because it is hidden by the parent view. Right now the best solution to go with Android is to use the v1.1.2 release until overflows are supported by RN for Android.

**Comment by edwinjue** [comment] 2016-09-25 21:08
Thanks @l-urence

**Comment by fab1an** [comment] 2016-10-02 15:14
I'm afraid it's not possible to solve this using a single component.

The dropdown list needs to be neighbour to the TextInput in order to be able to overlap other content.

I don't think this will change in upcoming versions of RN.

**Comment by l-urence** [comment] 2016-10-02 20:05
@fab1an just for Android? In iOS this works well.

**Comment by fab1an** [comment] 2016-10-02 21:48
Android has a very different rendering system than iOS

**Comment by DiegoGallegos4** [comment] 2016-12-05 19:51
If Autocomplete is sibling of other views it does not either: 
`
<View style={{flexDirection:'row', borderBottomWidth: 1, borderBottomColor: 'rgb(197,195,201)', alignItems: 'center', position: 'relative', zIndex: 1,backgroundColor: '#fff'}}>
            <View style={{flex: 1}}>
              ...
            </View>
              <Autocomplete
                autoCapitalize="none"
                autoCorrect={false}
                data={((visitors.length === 1 && comp(query, visitors[0].name)) || this.state.clicked) ? [] : visitors}
                defaultValue={query}
                containerStyle={{borderWidth: 0, zIndex: 1}}
                inputContainerStyle={{borderWidth: 0, margin: 0}}
                onChangeText={text => {this.setState({ query: text, clicked: false }); console.log(visitors)}}
                placeholder="Enter visitor name"
                listStyle={{zIndex: 1, position: 'absolute'}}
                style={{backgroundColor: 'transparent', fontSize: 14}}
                renderItem={({ name }) => (
                  <TouchableOpacity style={{padding: 5}} onPress={() => this.selectQueryListItem(query, true, name)}>
                    <Text>
                      {name} 
                    </Text>
                  </TouchableOpacity>
                )}
              />
            <TouchableOpacity 
              style={{backgroundColor: '#18AEC3', padding: 10}}
              onPress={()=>...}
            >
              ...
            </TouchableOpacity>
          </View>
`

**Comment by bozzmob** [comment] 2016-12-19 12:17
How about using -

https://gist.github.com/tioback/6af21db0685cd3b1de28b84981f31cca

as suggested here - facebook/react-native#6802

**Comment by l-urence** [comment] 2017-01-31 09:03
[v3.0.0](https://github.com/l-urence/react-native-autocomplete-input/releases/tag/v3.0.0) will simplify the integration into Android.

I will close this issue for now, because this is not going to change until there is some kind of support for overflows in RN for Android.

**Closed by l-urence** 2017-01-31 09:03 UTC

**Comment by gitpushdev** [comment] 2018-03-06 14:29
I'm still facing issue making it work, I'd appreciate if anyone can spot where I'm going wrong, auto complete list is displaying inside the container view and not outside of it
 
This is my code: 

```
<Autocomplete data={isDeparture ? this.state.departureFlightData : this.state.returnFlightData}
                defaultValue={isDeparture ? this.state.countryFrom : this.state.countryTo}
                hideResults={isDeparture ? this.state.hideDepartureFlightData : this.state.hideReturnFlightData}
                placeholder={strings.search_countries}
                listContainerStyle={{ width: '107.9%', zIndex: 99999999 }}
                underlineColorAndroid='transparent'
                containerStyle={{ width: '90%', borderWidth: 0, borderColor: 'transparent' }}
                inputContainerStyle={{ paddingLeft: 5, borderWidth: 0, borderColor: 'transparent' }}
                onChangeText={this.handleOnChange}
                renderItem={
                    item => (/.Item Component./)
                }
            />
```
```

<View style={[styles.contentContainer, { zIndex: 2 }]}>
<View style={[styles.cardRow, { zIndex: 2 }]}>
<View style={[styles.cardRow, { zIndex: 2 }]}>
~~~ AUTO COMPELTE IS RENDERED HERE ~~~~
</View>
</View>
</View>
```

Card Row style: 

 ```
flexDirection: 'row',
        height: 40,
        justifyContent: 'center',
        alignContent: 'center',
        alignItems: 'center',
        width: '100%',
        backgroundColor: '#FFFFFF',
        shadowOpacity: 1,
        shadowColor: '#cccccc',
        shadowOffset: { width: 1, height: 1 },
        elevation: 1
```

**Comment by gitpushdev** [comment] 2018-03-06 14:30
I'm still facing issue making it work, I'd appreciate if anyone can spot where I'm going wrong, auto complete list is displaying inside the container view and not outside of it. Working as expected on iOS
 
This is my code: 

```
<Autocomplete data={['data']}
                defaultValue={[]}
                hideResults={true}
                placeholder={strings.search_countries}
                listContainerStyle={{ width: '107.9%', zIndex: 99999999 }}
                underlineColorAndroid='transparent'
                containerStyle={{ width: '90%', borderWidth: 0, borderColor: 'transparent' }}
                inputContainerStyle={{ paddingLeft: 5, borderWidth: 0, borderColor: 'transparent' }}
                onChangeText={this.handleOnChange}
                renderItem={
                    item => (/.Item Component./)
                }
            />
```
```

<View style={[styles.contentContainer, { zIndex: 2 }]}>
<View style={[styles.cardRow, { zIndex: 2 }]}>
<View style={[styles.cardRow, { zIndex: 2 }]}>
~~~ AUTO COMPELTE IS RENDERED HERE ~~~~
</View>
</View>
</View>
```

Card Row style: 

 ```
flexDirection: 'row',
        height: 40,
        justifyContent: 'center',
        alignContent: 'center',
        alignItems: 'center',
        width: '100%',
        backgroundColor: '#FFFFFF',
        shadowOpacity: 1,
        shadowColor: '#cccccc',
        shadowOffset: { width: 1, height: 1 },
        elevation: 1
```

**Comment by Johnscorps** [comment] 2018-03-07 09:17
I added this line to the AutoComplete props, and it worked like a charm, hope this works for you too!

`listStyle={{zIndex: 1, position: 'absolute'}}`

**Comment by gitpushdev** [comment] 2018-03-07 13:10
It was my messed up view, fixed my views layout and now all is working, sorry for false alarm :)

**Comment by vandiepbui** [comment] 2019-05-17 03:59
> I added this line to the Autocomplete props, and it worked like a charm, hope this works for you too!
> 
> `listStyle={{zIndex: 1, position: 'absolute'}}`

Not work for me ! Pls anyone help me

![image](https://user-images.githubusercontent.com/35633954/57902323-e12ea680-7892-11e9-824a-aeb9dcd24d1a.png)

**Comment by cakesoft-nikhita-gawande** [comment] 2019-08-30 14:18
> > I added this line to the Autocomplete props, and it worked like a charm, hope this works for you too!
> > `listStyle={{zIndex: 1, position: 'absolute'}}`
> 
> Not work for me ! Pls anyone help me
> 
> ![image](https://user-images.githubusercontent.com/35633954/57902323-e12ea680-7892-11e9-824a-aeb9dcd24d1a.png)

any success??

**Comment by fungilation** [comment] 2019-09-05 21:36
Is the absolute positioning for Android in docs and examples in this repo still relevant? I see that overflow support has been added since RN 0.57: https://github.com/facebook/react-native/commit/b81c8b51fc6fe3c2dece72e3fe500e175613c5d4

**Comment by sorinbogdan95** [comment] 2019-10-28 11:16
Not working if it is put inside a parent component and the parent component has a sibling below it, even if autocomplete input's parent has position: absolute and zIndex set.

**Comment by Hashir524** [comment] 2019-12-02 11:30
I have tried every possible solution, suggested here. My Component is working fine on ios. But on android list is showing , i can't click. TouchableOpacity is not working. Instead the scroll is getting all the touch events, and other components. Any help would be much appreciated.

**Comment by thanhluantl2304** [comment] 2020-03-13 08:56
> I have tried every possible solution, suggested here. My Component is working fine on ios. But on android list is showing , i can't click. TouchableOpacity is not working. Instead the scroll is getting all the touch events, and other components. Any help would be much appreciated.

Me too, any update on this? I'm still waiting for the final solution.

**Comment by sabres207** [comment] 2020-04-01 01:08
> > I have tried every possible solution, suggested here. My Component is working fine on ios. But on android list is showing , i can't click. TouchableOpacity is not working. Instead the scroll is getting all the touch events, and other components. Any help would be much appreciated.
> 
> Me too, any update on this? I'm still waiting for the final solution.

same here, android fixes makes the options not clickable.

**Comment by alamorre** [comment] 2020-05-05 00:26
Same ...

**Comment by sachin3072004** [comment] 2020-05-08 02:20
Same here :(

**Comment by tayloraleach** [comment] 2020-05-14 21:00
same

**Comment by mixa63rus** [comment] 2020-05-26 15:20
same

**Comment by isidore18** [comment] 2020-06-04 15:47
`renderTextInput={(text) => (
                      <TextInput
                        placeholder={'Code postal*'}
                        style={{
                          flex: 1,
                          padding: 0,
                          color: 'lightgray',
                          marginTop: 7,
                          marginBottom: 5,
                          paddingRight: 11,
                          backgroundColor: '#f1f0f3',
                          borderRadius: scale(25),
                          width: '100%',
                          height: scale(50)
                        }}
                        onChangeText={(text) => {
                          setZipCodeQuery(text);
                        }}
                        value={zipCodeQuery}
                        defaultValue={zipCodeQuery}
                      />
                    )}`

**Comment by isidore18** [comment] 2020-06-04 15:51
Suggestions were not showing either.
Fixed it by adding renderTextInput prop to the autocomplete props

My example here :

renderTextInput={(text) => (
                      <TextInput
                        placeholder={'Code postal*'}
                        style={{
                          flex: 1,
                          padding: 0,
                          color: 'lightgray',
                          marginTop: 7,
                          marginBottom: 5,
                          paddingRight: 11,
                          backgroundColor: '#f1f0f3',
                          borderRadius: scale(25),
                          width: '100%',
                          height: scale(50)
                        }}
                        onChangeText={(text) => {
                          setZipChoosen(false);
                          setZipCodeQuery(text);
                          testZipCode(text);
                        }}
                        value={zipCodeQuery}
                        defaultValue={zipCodeQuery}
                      />
                    )}

**Comment by MythriJL** [comment] 2020-11-12 12:15
> I have tried every possible solution, suggested here. My Component is working fine on ios. But on android list is showing , i can't click. TouchableOpacity is not working. Instead the scroll is getting all the touch events, and other components. Any help would be much appreciated.

I also have the same problem, can some one reopen this issue

**Comment by VivekVithlani** [comment] 2020-12-16 10:34
Just add 1 line and problem solved.
`listStyle={{ position: 'relative' }}`

**### Before**
![Simulator Screen Shot - iPhone 11 - 2020-12-16 at 16 01 38](https://user-images.githubusercontent.com/8317975/102337177-27d90b00-3fb8-11eb-952d-cd904d6a70af.png)

### **After**
![Simulator Screen Shot - iPhone 11 - 2020-12-16 at 16 01 24](https://user-images.githubusercontent.com/8317975/102337192-30314600-3fb8-11eb-917f-fcaadc2ce488.png)

**Comment by msmfsd** [comment] 2021-02-11 02:52
Bump - @mrlaessig  any updates on this issue? Adding above suggestions and still cant select a list item on Android

**Comment by IvanTrutnev** [comment] 2021-02-24 13:24
> Bump - @mrlaessig any updates on this issue? Adding above suggestions and still cant select a list item on Android

the same

**Comment by msmfsd** [comment] 2021-02-26 22:47
@mrlaessig @IvanTrutnev yes I managed to get it to work using different styles for iOS and android. For iOS follow normal guide and for android make sure your container has position relative and set an implicit height, then your inner container should have position absolute:
`droidContainer: {
    position: 'relative',
    width: '100%',
    height: 120,
  },
  droidView: {
    width: '100%',
    position: 'absolute',
    zIndex: 1,
    flex: 1,
  }, `

**Comment by jakobwak** [comment] 2021-03-19 17:51
This workaround might fit for some. The approach is to grow the height of the parent View together with the result List. It behaves a little bit like an accordion then.  If you need to have it as a real overlay, it is not an option. 

`
        <View style={[hideResults ? {height: 90} : {height: 270}]}> 
                <Autocomplete
                  onShowResult={() => this.showResultCheck()}
                 onChangeText={text => this.changeValue(text)}
                ...
                >
       </View>

`

`    
  showResultCheck (){
            this.setState({hideResults : true})
   }
`

`
changeValue(text){
   this.setState({ hideResults: false });
    ...
}
`

In this way the result List does not Interfere with any touchable element in the background.

![Bildschirmfoto 2021-03-19 um 12 11 11](https://user-images.githubusercontent.com/2116058/111822174-c17bc580-88e3-11eb-8a0b-fc556b750d5d.png)

![Bildschirmfoto 2021-03-19 um 18 50 04](https://user-images.githubusercontent.com/2116058/111822328-f0923700-88e3-11eb-8c5d-2322c021df1b.png)

**Comment by jakobwak** [comment] 2021-03-19 17:54
This workaround might fit for some. The approach is to grow the height of the parent view together with the result List. It behaves a little bit like an accordion then. If you need to have the result list as a real overlay, it is not an option.

<View style={[hideResults ? {height: 90} : {height: 270}]}>
<Autocomplete
onShowResult={() => this.showResultCheck()}
onChangeText={text => this.changeValue(text)}
...
>

showResultCheck (){
this.setState({hideResults : true})
}

changeValue(text){
this.setState({ hideResults: false });
...
}

In this way the result List does not Interfere with any touchable element in the background.

![Bildschirmfoto 2021-03-19 um 18 48 46](https://user-images.githubusercontent.com/2116058/111822671-60a0bd00-88e4-11eb-95f4-562a1234aa66.png)
![Bildschirmfoto 2021-03-19 um 18 50 04](https://user-images.githubusercontent.com/2116058/111822669-60a0bd00-88e4-11eb-82c0-0620c13f7d8c.png)

**Comment by rabidkitten** [comment] 2021-05-08 23:28
This issue was opened in 2016 and it is now 2021 and the issue is still occurring. There needs to be a clear and concise fix. Like others have said, it appears that you can't click on an item on Android, whereas it works fine on iOS.

**Comment by mrlaessig** [comment] 2021-05-14 14:32
@rabidkitten I checked this with [example](https://snack.expo.io/@mrlaessig/rn-autocomplete-input-example) and it works at least on an emulator.
![image](https://user-images.githubusercontent.com/472753/118285282-953e8880-b4d1-11eb-96fc-7f28757ca549.png)

**Comment by rabidkitten** [comment] 2021-05-15 14:31
@mrlaessig I had the latest and I used the android emulator as well and I couldn't click or tap on an item. The drop down was working, but I couldn't select an item by tapping or clicking. I just gave up on the component altogether.

**Comment by mrlaessig** [comment] 2021-05-16 12:44
@rabidkitten This could happen if they keyboard is still open. Try to pass `keyboardShouldPersistTaps: 'always'` on `flatListProps`. See [example](https://snack.expo.io/@mrlaessig/rn-autocomplete-input-example).

**Comment by hlspablo** [comment] 2021-07-20 01:21
> I added this line to the Autocomplete props, and it worked like a charm, hope this works for you too!
> 
> `listStyle={{zIndex: 1, position: 'absolute'}}`

Thanks, worked Perfectly
